### ISSUE TITLE
Elhouse cover sensor and alarm

### ISSUE THREAD

**Issue by emilssp** [vortexntnu/vortex-asv-firmware#20]
### Time estimate (Hours)

3h

### Deadline (DD.MM)

24.09

### Description of task

Senses if Freyas elhouse cover is open and make sound if it is

### Specifications

- Measure distance 
- Trigger buzzer if distance is greater than the distance from the sensor to the lid

### Suggested Workflow

- measure distance sensor
- start buzzer

### Contacts

- Emilssp

**Comment by Benjamin-A** [comment]
It works
