### ISSUE TITLE
Implement Telemtry data system for ESC on the ASV

### ISSUE THREAD

**Issue by PizzaAllTheWay** [vortexntnu/vortex-asv-firmware#5]
Telemetri data for software

Telemtrey for ESC (voltage, current, temperature ect... see URL) 
Telemetry has unkown protocol -> Find out
- pin 11. Telemetry av ESC 1
- pin 12. Telemetry av ESC 2
- pin 13. Telemetry av ESC 3
- pin 14. Telemetry av ESC 4

Look at this libarar I found, for FrySky Smart.Port telemetry implementaion in Arduino :)
Use this:
https://github.com/zendes/SPort

**Comment by Benjamin-A** [comment]
bro this shit is stale, lmao, clozingggggggg jazzzz
