### ISSUE TITLE
Get BMS data else disqualified

### ISSUE THREAD

**Issue by PizzaAllTheWay** [vortexntnu/vortex-asv-firmware#6]
Electrical will implement 2 BMS (Battery Management System) for 2 batterie packs that manages batteries. This system then sends out Voltage and Temperature of the batteries data with RS485 protocol. Electrical will have a hardware solution that converts this protocol to USB. One USB for each BMS, so 2 USBs. These 2 USBs will be connected to Rock PI (https://ameridroid.com/products/rock-pi-4c) USB ports. Our task is to read data from USB connections on Rock PI, process it in a understandable manner and then publish it to ROS.

!NOTE! Failure of implementing BMS data gathering will result in Vortex being disqualified from Njord challenge!!!

**Comment by KristianSem** [comment]
With jbdtools in #13 we can read the bms data from both batteries. ROS implementation has been made in vortex-asv
