### ISSUE TITLE
Implement Teensy ROS Protocol

### ISSUE THREAD

**Issue by PizzaAllTheWay** [vortexntnu/vortex-asv-firmware#8]
Teensy I2C and SPI protocol can only handle so much data transfer. In order to have faster and more accurate controls of thrusters we need to implement a faster protocol to send data through. ROS Micro is a good starting point as it is an extension of Ethernet IP protocol, like TCP and UDP is. It will also help scale data rate when sending a lot of data from ESC telemetry and acoustics data.

**Comment by theBadMusician** [comment]
Strongly disagree with this, SPI is able to deliver up to 100 Mb/s (10 Mb/s is common) and as we are going to run the commands to thrusters at around 10 Hz there is no need to use any high-level protocols such as Ethernet. There are going to be two separate Teensies for acoustics and the motor driver.

In addition, as you've mentioned yourself, the motor driver needs to be able to deliver commands in a fast manner, which is the whole purpose of low-level protocols such as I2C and SPI. Ethernet, and other higher-level protocols require too much infrastructure, and by extension, have too much delay to be used effectively in motor control applications.

Are there any other particular reasons for not using I2C or SPI for this purpose?
